#!/bin/bash

dirctory=/bin

if [ -d $directory ]; then
  echo "The installation of $package was successful."
  echo "The new command is available here:"
  which $package
else
  echo "$package failed to install." >> package_install_failure.log

fi
